---
upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
  showcase:
    default_front_matter_template: showcase
  functions:
    default_front_matter_template: functions
version: 0.38.1
