---
hide_body: false
fields:
- name: linktitle
  label: Linktitle
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- name: godocref
  label: Godocref
  type: text
  hidden: false
  default: ''
- name: publishdate
  label: Publishdate
  type: text
  hidden: false
  default: ''
- name: lastmod
  label: Lastmod
  type: text
  hidden: false
  default: ''
- name: categories
  label: Categories
  type: tag_list
  hidden: false
  default: []
- name: tags
  label: Tags
  type: list
  hidden: false
  default: []
- name: weight
  label: Weight
  type: text
  hidden: false
  default: 0
- name: slug
  label: Slug
  type: text
  hidden: false
  default: ''
- name: aliases
  label: Aliases
  type: list
  hidden: false
  default: []
- name: toc
  label: Toc
  type: boolean
  hidden: false
  default: false
